"""
heatmap.py — Visualise where the trained cat spent its time.

Run from the catrl/ root directory AFTER running evaluate.py:
    python viz/heatmap.py

Reads:  logs/visit_counts.npy  (generated by evaluate.py)
Saves:  logs/heatmap.png
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap

from env.cat_env import (
    EMPTY, WALL, SUNNY_SPOT, FOOD_BOWL, TOY,
    TABLE_OBJ, BOX, VET_CARRIER, HUMAN, CatEnv
)

# ──────────────────────────────────────────────────────────────
#  LOAD DATA
# ──────────────────────────────────────────────────────────────
VISIT_PATH = "logs/visit_counts.npy"

if not os.path.exists(VISIT_PATH):
    print("ERROR: logs/visit_counts.npy not found.")
    print("Run  python evaluate/evaluate.py  first to generate it.")
    sys.exit(1)

visit_counts = np.load(VISIT_PATH)

# Rebuild the map to overlay cell labels
env      = CatEnv()
grid_map = env._build_map()
env.close()

# ──────────────────────────────────────────────────────────────
#  PLOT
# ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor("#1a1a2e")

# ── LEFT: raw visit heatmap ───────────────────────────────────
ax1 = axes[0]
cat_cmap = LinearSegmentedColormap.from_list(
    "cat", ["#1a1a2e", "#4a3060", "#9b59b6", "#f39c12", "#f1c40f"]
)
im = ax1.imshow(visit_counts, cmap=cat_cmap, interpolation="nearest")
plt.colorbar(im, ax=ax1, label="Visit count")

ax1.set_title("Where the cat spent its time", color="white", pad=12, fontsize=13)
ax1.set_xlabel("Column", color="#aaa")
ax1.set_ylabel("Row", color="#aaa")
ax1.tick_params(colors="#aaa")
for spine in ax1.spines.values():
    spine.set_edgecolor("#444")

# overlay cell-type markers
CELL_MARKERS = {
    SUNNY_SPOT:  ("☀",  "gold"),
    FOOD_BOWL:   ("🍲",  "lightgreen"),
    TOY:         ("🎾",  "orange"),
    TABLE_OBJ:   ("📦",  "tan"),
    BOX:         ("■",   "#d4aa55"),
    VET_CARRIER: ("⚕",   "red"),
    HUMAN:       ("👤",  "lightblue"),
}

for r in range(env.GRID_H):
    for c in range(env.GRID_W):
        cell = grid_map[r, c]
        if cell == WALL:
            ax1.add_patch(plt.Rectangle((c - 0.5, r - 0.5), 1, 1,
                                         color="#333", zorder=2))
        if cell in CELL_MARKERS:
            sym, col = CELL_MARKERS[cell]
            ax1.text(c, r, sym, ha="center", va="center",
                     fontsize=9, color=col, zorder=3)

# ── RIGHT: normalised heatmap + grid overlay ──────────────────
ax2 = axes[1]
norm_visits = visit_counts / (visit_counts.max() + 1e-8)
im2 = ax2.imshow(norm_visits, cmap="hot", interpolation="bilinear",
                  vmin=0, vmax=1)
plt.colorbar(im2, ax=ax2, label="Relative visit frequency")

ax2.set_title("Relative visit frequency (smoothed)", color="white",
              pad=12, fontsize=13)
ax2.set_xlabel("Column", color="#aaa")
ax2.tick_params(colors="#aaa")
for spine in ax2.spines.values():
    spine.set_edgecolor("#444")

# draw grid lines
for x in range(env.GRID_W + 1):
    ax2.axvline(x - 0.5, color="#555", linewidth=0.4)
for y in range(env.GRID_H + 1):
    ax2.axhline(y - 0.5, color="#555", linewidth=0.4)

# ──────────────────────────────────────────────────────────────
#  STATISTICS ANNOTATION
# ──────────────────────────────────────────────────────────────
total_visits  = visit_counts.sum()
top_cells_idx = np.argsort(visit_counts.ravel())[-5:][::-1]

print("\nTop 5 most visited cells:")
for idx in top_cells_idx:
    r, c = divmod(idx, env.GRID_W)
    cell = grid_map[r, c]
    name = {EMPTY: "floor", SUNNY_SPOT: "sunny spot", FOOD_BOWL: "food bowl",
            TOY: "toy", TABLE_OBJ: "table obj", BOX: "box",
            VET_CARRIER: "VET CARRIER (!)", HUMAN: "human"}.get(cell, "?")
    print(f"  ({r:2d}, {c:2d})  {name:<15}  visits: {visit_counts[r, c]:4d}  "
          f"({visit_counts[r, c]/total_visits*100:.1f}%)")

# ── suptitle ──────────────────────────────────────────────────
fig.suptitle("CatRL — Learned Behaviour Heatmap",
             color="white", fontsize=15, y=1.02)

plt.tight_layout()

os.makedirs("logs", exist_ok=True)
save_path = "logs/heatmap.png"
plt.savefig(save_path, dpi=150, bbox_inches="tight",
            facecolor=fig.get_facecolor())
print(f"\nHeatmap saved to {save_path}")
plt.show()